export const placeServices = {
    "Dịch vụ": ["Thực phẩm"],
    "Thú cưng": ["Cho phép mang theo chó"],
    "Trẻ em": [
        "Phù hợp cho trẻ em",
        "Hoạt động phù hợp với trẻ em",
        "Chương trình chiết khấu cho trẻ em",
        "Giảm giá cho gia đình",
        "Phù hợp cho tiệc sinh nhật của trẻ em",
        "Sân chơi",
    ],
    "Bãi đỗ xe": [
        "Bãi đỗ xe có tính phí",
        "Gara đỗ xe miễn phí",
        "Đỗ xe miễn phí trên đường",
        "Bãi đỗ xe miễn phí",
        "Chỗ đỗ xe trong khuôn viên",
    ],
    "Lên kế hoạch": ["Bạn nên đặt vé trước", "Yêu cầu hẹn trước"],
    "Điểm nổi bật": ["Biểu diễn trực tiếp"],
    "Phù hợp cho người khuyết tật": [
        "Lối vào cho xe lăn",
        "Chỗ đỗ xe cho xe lăn",
        "Nhà vệ sinh cho xe lăn",
        "Chỗ ngồi cho xe lăn",
        "Vòng trợ thính",
        "Âm thanh truyền bằng công nghệ Auracast",
    ],
    "Tiện nghi": [
        "Nhà hàng",
        "Wi-Fi miễn phí",
        "Giữ hộ hành lý",
        "Wi-Fi",
        "Nhà vệ sinh",
        "Nhà vệ sinh cho cả hai giới",
    ],
    "Khách hàng": [
        "Nơi an toàn cho người chuyển giới",
        "Dành cho gia đình",
        "Chào đón những người thuộc giới LGBTQ",
    ],
    "Các tùy chon dịch vụ": ["Dịch vụ tại chỗ"],
}