export const roomServices = {
    "Phòng ngủ": [
        "Giường cực dài (> 2 mét)",
        "Tủ hoặc phòng để quần áo",
        "Ra trải giường",
        "Đồng hồ báo thức",
        "Phòng thay quần áo",
    ],
    "Tổng quát": [
        "Khu vực cho phép hút thuốc",
        "Sàn trải thảm",
        "Chăn điện",
        "Phòng không gây dị ứng",
        "Tiện nghi cho khách khuyết tật",
        "Nhà thờ/miếu thờ",
        "Sàn lát gỗ",
        "Phòng cách âm",
        "Xe đưa đón sân bay",
        "Điều hòa không khí",
        "Thang máy",
        "Quyền sử dụng Executive Lounge",
        "Cho thuê xe hơi",
        "Chỗ ngủ cho vật nuôi",
        "Có phòng thông nhau qua cửa nối",
        "Sàn lát gạch/đá cẩm thạch",
        "Két an toàn cỡ laptop",
        "Hiệu cắt tóc/làm đẹp",
        "Khu vực xem TV/sảnh chung",
        "Điều hòa nhiệt độ",
        "Cửa hàng tạp hóa (trong khuôn viên)",
        "Bàn ủi",
        "Phòng không hút thuốc",
        "Bàn ủi li quần",
        "Giao nhận đồ tạp hóa",
        "Không gây dị ứng",
        "Tiện nghi ủi",
        "Cấm hút thuốc trong toàn bộ khuôn viên",
        "Máy bán hàng tự động (đồ ăn nhẹ)",
        "Bát ăn cho vật nuôi",
        "Lối vào riêng",
        "Máy bán hàng tự động (đồ uống)",
        "Hệ thống cách âm",
        "Dịch vụ báo thức",
        "Phòng gia đình",
        "Bữa trưa đóng hộp",
        "Thiết bị báo carbon monoxide",
        "Quạt máy",
        "Màn chống muỗi",
        "Hệ thống sưởi",
        "Chỉ dành cho người lớn",
        "Dịch vụ đưa đón",
        "Dịch vụ báo thức",
        "Dịch vụ phòng",
    ],
    "Dịch vụ & Khoản phụ": [
        "Quyền sử dụng Executive Lounge",
        "Dịch vụ báo thức",
    ],
    "Phương tiện đi lại": [
        "Cho thuê xe hơi",
        "Cho thuê xe đạp",
        "Xe đưa đón sân bay",
        "Dịch vụ đưa đón",
        "Vé đi phương tiện công cộng",
    ],
    "Đặc tính tòa nhà": ["Đơn lập", "Căn hộ riêng trong tòa nhà", "Song lập"],
    "Đồ ăn & thức uống": [
        "Quán cà phê (trong khuôn viên)",
        "Thực đơn ăn kiêng đặc biệt (theo yêu cầu)",
        "Giao nhận đồ tạp hóa",
        "Máy bán hàng tự động (đồ uống)",
        "Minibar",
        "Quầy bar (đồ ăn nhẹ)",
        "Nhà hàng",
        "Trái cây",
        "Bữa sáng tại phòng",
        "Quầy bar",
        "Bữa ăn trẻ em",
        "Bữa trưa đóng hộp",
        "Bữa ăn tự chọn phù hợp với trẻ em",
        "Máy pha trà/cà phê",
        "Rượu vang/sâm panh",
        "Dịch vụ phòng",
    ],
    "Khu vực chung": ["Khu vực xem TV/sảnh chung", "Phòng chơi game"],
    "Tiện ích trong phòng": [
        "Lối vào riêng",
        "Điều hòa không khí",
        "Sàn lát gạch/đá cẩm thạch",
        "Giá treo quần áo",
        "Màn chống muỗi",
        "Giường sofa",
        "Giường xếp",
        "Quạt máy",
        "Không gây dị ứng",
        "Giá phơi quần áo",
        "Tiện nghi ủi",
        "Bàn ủi",
        "Ổ điện gần giường",
        "Có phòng thông nhau qua cửa nối",
        "Bàn ủi li quần",
        "Sàn trải thảm",
        "Sàn lát gỗ",
        "Hệ thống cách âm",
        "Hệ thống sưởi",
    ],
    "Dịch vụ cho doanh nhân": [
        "Trung tâm dịch vụ doanh nhân",
        "Tiện nghi tổ chức hội họp/tiệc",
        "Fax/photocopy",
    ],
    "Phòng tắm": [
        "Dép",
        "Bồn tắm",
        "Phòng tắm chung",
        "Khăn tắm",
        "Toilet chung",
        "Vòi sen",
        "Khăn tắm/Bộ khăn trải giường (có thu phí)",
        "Bồn tắm hoặc Vòi sen",
        "Phòng tắm phụ",
        "Giấy vệ sinh",
        "Chậu rửa vệ sinh (bidet)",
        "Phòng tắm riêng",
        "Áo choàng tắm",
        "Máy sấy tóc",
        "Toilet phụ",
        "Bồn tắm spa",
        "Đồ vệ sinh cá nhân miễn phí",
        "Nhà vệ sinh",
    ],
    "Dịch vụ": [
        "Lễ tân 24 giờ",
        "Giặt ủi",
        "Xe đưa đón sân bay",
        "Dịch vụ trợ giúp đặc biệt",
        "Khu vực xem TV/sảnh chung",
        "Nhận/trả phòng riêng",
        "Giao nhận đồ tạp hóa",
        "Dọn phòng hàng ngày",
        "Dịch vụ báo thức",
        "Tủ khóa",
        "Thu đổi ngoại tệ",
        "Dịch vụ đưa đón",
        "Giữ hành lí",
        "Máy ATM/rút tiền trong khuôn viên",
        "Fax/photocopy",
        "Máy bán hàng tự động (đồ uống)",
        "Giặt khô",
        "Nhận/trả phòng cấp tốc",
        "Dịch vụ phòng",
        "Bàn bán tour",
        "Tiện nghi tổ chức hội họp/tiệc",
        "Dịch vụ là (ủi)",
        "Hiệu cắt tóc/làm đẹp",
        "Bàn ủi li quần",
        "Cho thuê xe hơi",
        "Dịch vụ báo thức",
    ],
    "Lối vào dành cho người khuyết tật": [
        "Xe lăn có thể đi đến mọi nơi trong toàn bộ khuôn viên",
        "Dây khẩn cấp trong phòng tắm",
        "Bồn rửa mặt thấp hơn",
        "Các tầng trên chỉ lên được bằng cầu thang",
        "Lối vào cho người đi xe lăn",
        "Tiện ích hỗ trợ người khiếm thính",
        "Các tầng trên đi lên bằng thang máy",
        "Hỗ trợ khiếm thị: Braille",
        "Hoàn toàn nằm ở tầng trệt",
        "Hướng dẫn bằng âm thanh",
        "Hỗ trợ khiếm thị: Dấu hiệu nổi",
        "Toilet dành cho người khuyết tật",
        "Toilet có sàn cao hơn",
    ],
    "Hồ bơi trong nhà": [
        "Dành cho mọi độ tuổi",
        "Chỉ dành cho người lớn",
        "Khăn hồ bơi/bãi biển",
        "Theo mùa",
        "Ô (dù) che nắng loại to",
        "Giờ mở cửa",
        "Cầu trượt nước",
        "Hàng rào quanh hồ bơi",
        "Ghế/ghế dài tắm nắng",
        "Hồ bơi nước nóng",
        "Quầy bar hồ bơi",
        "Chỗ cạn",
        "Hồ bơi nước mặn",
        "Mái che hồ bơi",
        "Đồ chơi ở hồ bơi",
        "Mở cửa quanh năm",
        "Hồ bơi có tầm nhìn",
        "Hồ bơi trên sân thượng",
        "Hồ bơi vô cực",
    ],
    "Khu vực phòng khách": [
        "Khu vực tiếp khách",
        "Lò sưởi",
        "Khu vực phòng ăn",
        "Ghế sofa",
        "Bàn làm việc",
    ],
    "An ninh": [
        "Hệ thống CCTV trong khu vực chung",
        "Báo động an ninh",
        "Ổ khóa mở bằng thẻ",
        "Ổ khóa",
        "Hệ thống CCTV bên ngoài chỗ nghỉ",
        "Két an toàn",
        "Thiết bị báo cháy",
        "Bình chữa cháy",
        "Bảo vệ 24/7",
        "Thiết bị báo carbon monoxide",
    ],
    "Dịch vụ giải trí và gia đình": [
        "Khu vui chơi trong nhà",
        "Câu lạc bộ trẻ em",
        "Dịch vụ trông giữ trẻ em",
        "Karaoke",
        "Xe đẩy",
        "Nắp che ổ cắm điện an toàn",
        "Trò chơi Board games/giải đố",
        "Sòng bạc",
        "Thiết bị vui chơi ngoài trời cho trẻ em",
        "Sách, đĩa DVD và nhạc cho trẻ em",
        "Trò chơi board game/giải đố",
        "Nhân viên Giải trí",
        "Cửa an toàn cho trẻ nhỏ",
        "Giải trí buổi tối",
        "Sân chơi trẻ em",
    ],
    "Tầm nhìn": [
        "Nhìn ra hồ",
        "Nhìn ra biển",
        "Nhìn ra thành phố",
        "Nhìn ra sông",
        "Nhìn ra hồ bơi",
        "Nhìn ra địa danh nổi tiếng",
        "Nhìn ra vườn",
        "Hướng nhìn sân trong",
        "Tầm nhìn ra khung cảnh",
        "Nhìn ra núi",
    ],
    "Cửa hàng": ["Cửa hàng tạp hóa (trong khuôn viên)", "Hiệu cắt tóc/làm đẹp"],
    "Hồ bơi - ngoài trời (dành cho trẻ em)": [
        "Chỗ cạn",
        "Ghế/ghế dài tắm nắng",
        "Phù hợp cho trẻ em",
        "Mở cửa quanh năm",
        "Ô (dù) che nắng loại to",
        "Giờ mở cửa",
        "Khăn hồ bơi/bãi biển",
    ],
    "Chăm sóc sức khỏe": [
        "Chăm sóc tóc",
        "Phòng gym",
        "Massage",
        "Nhuộm tóc",
        "Phòng tắm không gian mở",
        "Lớp học yoga",
        "Dịch vụ trang điểm",
        "Lớp thể dục",
        "Mát-xa tay",
        "Mát-xa chân",
        "Bồn tắm hơi/kiểu Thổ Nhĩ Kỳ",
        "Liệu pháp ánh sáng",
        "Cầu trượt nước",
        "Phòng tắm nắng",
        "Phòng gửi đồ ở spa/gym",
        "Dịch vụ ngâm chân",
        "Huấn luyện viên cá nhân",
        "Ghế/ghế dài tắm nắng",
        "Dịch vụ triệt lông",
        "Mát-xa lưng",
        "Hồ bơi trẻ em",
        "Mát-xa cổ",
        "Trung tâm Spa & chăm sóc sức khoẻ",
        "Ô (dù) che nắng loại to",
        "Trung tâm thể dục",
        "Cắt tóc",
        "Tắm suối nước nóng",
        "Mát-xa toàn thân",
        "Quấn toàn thân",
        "Tẩy tế bào chết toàn thân",
        "Dịch Vụ Làm Đẹp",
        "Tạo kiểu tóc",
        "Bồn tắm nóng/bể sục (Jacuzzi)",
        "Tiện Nghi Spa",
        "Gói spa/chăm sóc sức khỏe",
        "Mát-xa dành cho cặp đôi",
        "Khu vực thư giãn/spa lounge",
        "Phòng xông hơi ướt",
        "Mát-xa đầu",
        "Phòng tắm chung",
        "Dịch vụ làm móng tay",
        "Dịch vụ làm móng chân",
        "Trị Liệu Cơ Thể",
        "Phòng xông hơi",
        "Chăm sóc da mặt",
        "Ghế mát-xa",
    ],
    "Truyền thông & Công nghệ": [
        "Máy vi tính",
        "Máy fax",
        "TV màn hình phẳng",
        "Dịch vụ streaming (như là Netflix)",
        "Truyền hình cáp",
        "Đài radio",
        "Két an toàn cỡ laptop",
        "TV",
        "Truyền hình vệ tinh",
        "Ổ cắm cho iPod",
        "Truyền hình trả tiền",
        "Đầu video",
        "Điện thoại",
    ],
    "Ngoài trời & Tầm nhìn": [
        "Nhìn ra vườn",
        "Nhìn ra thành phố",
        "Hướng nhìn sân trong",
        "Nhìn ra địa danh nổi tiếng",
        "Nhìn ra biển",
        "Nhìn ra núi",
        "Nhìn ra sông",
        "Nhìn ra hồ",
        "Nhìn ra hồ bơi",
        "Tầm nhìn ra khung cảnh",
    ],
    "Dịch vụ lễ tân": [
        "Tủ khóa",
        "Nhận/trả phòng cấp tốc",
        "Thu đổi ngoại tệ",
        "Lễ tân 24 giờ",
        "Nhận/trả phòng riêng",
        "Dịch vụ trợ giúp đặc biệt",
        "Máy ATM/rút tiền trong khuôn viên",
        "Bàn bán tour",
        "Có xuất hóa đơn",
        "Giữ hành lí",
    ],
    "Hồ bơi ngoài trời": [
        "Hồ bơi vô cực",
        "Đồ chơi ở hồ bơi",
        "Hồ bơi nước mặn",
        "Hồ bơi có tầm nhìn",
        "Hồ bơi nước nóng",
        "Mở cửa quanh năm",
        "Mái che hồ bơi",
        "Chỉ dành cho người lớn",
        "Khăn hồ bơi/bãi biển",
        "Hàng rào quanh hồ bơi",
        "Chỗ cạn",
        "Quầy bar hồ bơi",
        "Ghế/ghế dài tắm nắng",
        "Dành cho mọi độ tuổi",
        "Theo mùa",
        "Bể ngâm",
        "Cầu trượt nước",
        "Ô (dù) che nắng loại to",
        "Giờ mở cửa",
        "Hồ bơi trên sân thượng",
    ],
    "Nhà bếp": [
        "Tủ lạnh",
        "Bếp nấu",
        "Sản phẩm lau rửa",
        "Đồ bếp",
        "Bếp nhỏ",
        "Ghế cao dành cho trẻ em",
        "Lò nướng",
        "Máy sấy quần áo",
        "Bếp",
        "Máy giặt",
        "Máy pha Cà phê",
        "Máy rửa bát",
        "Bàn ăn",
        "Ấm đun nước điện",
        "Máy nướng bánh mỳ",
        "Bếp chung",
        "Lò vi sóng",
    ],
    "2 hồ bơi": [
        "Hồ bơi trên sân thượng",
        "Quầy bar hồ bơi",
        "Hồ bơi vô cực",
        "Đồ chơi ở hồ bơi",
        "Phù hợp cho trẻ em",
        "Giờ mở cửa",
        "Khăn hồ bơi/bãi biển",
        "Chỗ cạn",
        "Mở cửa quanh năm",
        "Dành cho mọi độ tuổi",
        "Ô (dù) che nắng loại to",
        "Mái che hồ bơi",
        "Hồ bơi nước mặn",
        "Hồ bơi có tầm nhìn",
        "Hàng rào quanh hồ bơi",
        "Chỉ dành cho người lớn",
        "Ghế/ghế dài tắm nắng",
    ],
    "Ngoài trời": [
        "Sân hiên",
        "Khu vực bãi tắm riêng",
        "Khu vực ăn uống ngoài trời",
        "Sân hiên phơi nắng",
        "Hồ bơi riêng",
        "Ban công",
        "Bàn ghế ngoài trời",
        "Sân trong",
        "Lò sưởi ngoài trời",
        "Tiện nghi BBQ",
        "Giáp biển",
        "Sân vườn",
        "Khu vực picnic",
        "Tiện nghi BBQ",
        "Sân thượng / hiên",
    ],
    "Dịch vụ lau dọn": [
        "Dịch vụ là (ủi)",
        "Dọn phòng hàng ngày",
        "Giặt khô",
        "Bàn ủi li quần",
        "Giặt ủi",
    ],
    "Hoạt động": [
        "Giờ vàng",
        "Giải trí buổi tối",
        "Tour đi bộ",
        "Câu lạc bộ trẻ em",
        "Thiết bị dành cho cầu lông",
        "Bóng bàn",
        "Lặn",
        "Bóng quần (Squash)",
        "Nhảy/khám phá bar",
        "Lướt ván buồm",
        "Sân chơi trẻ em",
        "Thiết bị dành cho tennis",
        "Sân gôn (trong vòng 3km)",
        "Bữa tối theo chủ đề",
        "Nhân viên Giải trí",
        "Tour/lớp về văn hóa địa phương",
        "Cho thuê xe đạp",
        "Sân gôn mini",
        "Sòng bạc",
        "Bắn cung",
        "Lặn với ống thở",
        "Cưỡi ngựa",
        "Đêm phim",
        "Hài độc thoại",
        "Sự kiện thể thao (truyền hình trực tiếp)",
        "Bingo",
        "Bãi biển",
        "Tour đi xe đạp",
        "Bowling",
        "Câu cá",
        "Vũ trường/DJ",
        "Lớp dạy nấu ăn",
        "Công viên nước",
        "Ca-nô",
        "Karaoke",
        "Sân tennis",
        "Bể sục",
        "Xe đạp",
        "Bida",
        "Biểu diễn/nhạc sống",
        "Thể dục nhịp điệu (aerobic)",
        "Phi tiêu",
        "Đi bộ đường dài",
        "Tiện nghi chơi thể thao dưới nước (trong khuôn viên)",
        "Phòng chơi game",
        "Triển lãm tranh đương đại",
    ],
    "Chỗ đậu xe": [
        "Trạm sạc xe điện",
        "Dịch vụ đỗ xe cho khách",
        "Bãi đậu xe tiếp cận người khuyết tật",
        "Nhà để xe",
        "Chỗ đậu xe ngoài đường",
    ],
    "Các tiện nghi khác": [
        "Chỉ dành cho người lớn",
        "Điều hòa nhiệt độ",
        "Toilet có sàn cao hơn",
        "Hỗ trợ khiếm thị: Dấu hiệu nổi",
        "Dây khẩn cấp trong phòng tắm",
        "Bát ăn cho vật nuôi",
        "Cấm hút thuốc trong toàn bộ khuôn viên",
        "Chỗ ngủ cho vật nuôi",
        "Phòng gia đình",
        "Bồn rửa mặt thấp hơn",
        "Thang máy",
        "Toilet dành cho người khuyết tật",
        "Tiện nghi cho khách khuyết tật",
        "Hệ thống sưởi",
        "Phòng cách âm",
        "Phòng không gây dị ứng",
        "Khu vực cho phép hút thuốc",
        "Hướng dẫn bằng âm thanh",
        "Hỗ trợ khiếm thị: Braille",
        "Phòng không hút thuốc",
        "Lối vào cho người đi xe lăn",
    ],
}
