spring.application.name=AI-Hotel
spring.datasource.url=jdbc:postgresql://dpg-cvt5llc9c44c73ccctn0-a.oregon-postgres.render.com:5432/database_ft72
spring.datasource.username=chinh
spring.datasource.password=PL7F7BbwUbeZEIeZ4iYejgA7fMr5K5E1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.jdbc.batch_size=50
#spring.jpa.properties.hibernate.order_inserts=true

spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Server
server.port=8080